name: Build
on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build
        run: |
          sudo bash build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.event.repository.name }}-${{ matrix.runs-on }}"
          path: |
            Roobi.img